export const CAMERA_KIT_DEFAULT_LENS_GROUP_ID =
  process.env.NEXT_PUBLIC_CAMERA_KIT_LENS_GROUP_ID ?? "1b47fd82-8509-45af-974e-192a3646ea15"

const CAMERA_KIT_STAGING_TOKEN =
  process.env.NEXT_PUBLIC_CAMERA_KIT_STAGING_TOKEN ??
  "eyJhbGciOiJIUzI1NiIsImtpZCI6IkNhbnZhc1MyU0hNQUNQcm9kIiwidHlwIjoiSldUIn0.eyJhdWQiOiJjYW52YXMtY2FudmFzYXBpIiwiaXNzIjoiY2FudmFzLXMyc3Rva2VuIiwibmJmIjoxNzQ3OTcyNjYwLCJzdWIiOiI0MGFkMTIwMC1lMzBiLTRhZGEtYTk2Yi04YzhhYjc2Yzg3OWN-U1RBR0lOR34yNmZiZjMwYi02MDEyLTQxMTQtYTYyZS1iMDg1ZDMzOGViNGEifQ.Aqc9IChl6LbBFHVBY8G2tRwRA8-CehoPHAA7ocW9LqQ"

const CAMERA_KIT_PRODUCTION_TOKEN =
  process.env.NEXT_PUBLIC_CAMERA_KIT_PRODUCTION_TOKEN ??
  "eyJhbGciOiJIUzI1NiIsImtpZCI6IkNhbnZhc1MyU0hNQUNQcm9kIiwidHlwIjoiSldUIn0.eyJhdWQiOiJjYW52YXMtY2FudmFzYXBpIiwiaXNzIjoiY2FudmFzLXMyc3Rva2VuIiwibmJmIjoxNzQ3OTcyNjYwLCJzdWIiOiI0MGFkMTIwMC1lMzBiLTRhZGEtYTk2Yi04YzhhYjc2Yzg3OWN-UFJPRFVDVElPTn5mOGZmOWIxNi1hYjAyLTQyMDAtYTAxYy00MTMxMTMzMjNhNTIifQ.yHPsgcdaKG1Nwm1ShkJCurf-Bk30rqTbw0VvHUUxhWE"

const CAMERA_KIT_ENV = (process.env.NEXT_PUBLIC_CAMERA_KIT_ENV ?? "staging").toLowerCase()

export const CAMERA_KIT_TOKENS = {
  staging: CAMERA_KIT_STAGING_TOKEN,
  production: CAMERA_KIT_PRODUCTION_TOKEN,
} as const

export function getCameraKitToken() {
  if (CAMERA_KIT_ENV === "production") {
    return CAMERA_KIT_TOKENS.production
  }

  return CAMERA_KIT_TOKENS.staging
}

